// Re-export shim so `@canva/connect-api-ts/types.gen` resolves under classic
// (node10) moduleResolution, which ignores the package.json "exports" field.
// The generated sources live in ./ts (regenerated by `npm run openapi:generate`);
// this file sits at the package root so it survives `rm -rf ./ts`.
export * from "./ts/types.gen";
