// This file is auto-generated by @hey-api/openapi-ts

export const OwnershipTypeEnum = {
    ANY: 'ANY',
    OWNED: 'OWNED',
    SHARED: 'SHARED'
} as const;

export const SortByTypeEnum = {
    RELEVANCE: 'RELEVANCE',
    MODIFIED_DESCENDING: 'MODIFIED_DESCENDING',
    MODIFIED_ASCENDING: 'MODIFIED_ASCENDING',
    TITLE_DESCENDING: 'TITLE_DESCENDING',
    TITLE_ASCENDING: 'TITLE_ASCENDING'
} as const;

/**
 * State of the import job for an uploaded asset.
 */
export const ImportStatusStateEnum = {
    FAILED: 'FAILED',
    IN_PROGRESS: 'IN_PROGRESS',
    SUCCESS: 'SUCCESS'
} as const;

/**
 * A short string indicating why the upload failed. This field can be used to handle errors programmatically.
 *
 */
export const ImportErrorCodeEnum = {
    FILE_TOO_BIG: 'FILE_TOO_BIG',
    IMPORT_FAILED: 'IMPORT_FAILED'
} as const;

/**
 * Status of the design autofill job.
 */
export const DesignAutofillStatusEnum = {
    IN_PROGRESS: 'IN_PROGRESS',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
} as const;

/**
 * The access of the user, group, or team. This can be one of the following:
 *
 * - `NONE`: They have no explicit access to the design.
 * - `VIEWER`: They have access to list and view the design.
 * - `COMMENTER`: They have access to list, view, and comment on the design.
 * - `EDITOR`: They have access to:
 * - List or view the design.
 * - Make changes to the design's metadata and content.
 * - Add, update, and remove the access of others (except the design's owner).
 * - `OWNER`: They have access to:
 * - List and view the design.
 * - Make changes to the design's metadata and content.
 * - Add, update, and remove the access of others.
 * - Delete ([Trash](https://www.canva.com/help/delete-designs/)) the design.
 *
 * **Note**: Collaboration links allow users to view or edit a design regardless of the access role assigned to the user.
 */
export const DesignRoleEnum = {
    NONE: 'NONE',
    VIEWER: 'VIEWER',
    COMMENTER: 'COMMENTER',
    EDITOR: 'EDITOR',
    OWNER: 'OWNER'
} as const;

/**
 * Who has permission to use the Collaboration link. This can be one of the following:
 *
 * - `ANYONE`: Any Canva user with the Collaboration link.
 * - `OWNING_TEAM`: Any Canva user who is in the same Canva team as the design's owner,
 * and has the Collaboration link.
 */
export const CollaborationLinkVisibilityEnum = {
    ANYONE: 'ANYONE',
    OWNING_TEAM: 'OWNING_TEAM'
} as const;

/**
 * Status of the design generation job.
 */
export const DesignGenerationStatusEnum = {
    FAILED: 'FAILED',
    IN_PROGRESS: 'IN_PROGRESS',
    SUCCESS: 'SUCCESS'
} as const;

/**
 * Status of the design resize job.
 */
export const DesignResizeStatusEnum = {
    IN_PROGRESS: 'IN_PROGRESS',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED'
} as const;

/**
 * State of the design import job.
 */
export const DesignImportStatusStateEnum = {
    FAILED: 'FAILED',
    IMPORTING: 'IMPORTING',
    SUCCESS: 'SUCCESS'
} as const;

/**
 * A short string about why the import failed. You can programmatically
 * handle errors using this field.
 */
export const DesignImportErrorCodeEnum = {
    DESIGN_CREATION_THROTTLED: 'DESIGN_CREATION_THROTTLED',
    DESIGN_IMPORT_THROTTLED: 'DESIGN_IMPORT_THROTTLED',
    DUPLICATE_IMPORT: 'DUPLICATE_IMPORT',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    INVALID_FILE: 'INVALID_FILE'
} as const;

export const DesignTypeUnitsEnum = {
    PIXELS: 'PIXELS',
    CENTIMETERS: 'CENTIMETERS',
    MILLIMETERS: 'MILLIMETERS',
    INCHES: 'INCHES'
} as const;

/**
 * The export status of the job. A newly created job will be `IN_PROGRESS` and will eventually
 * become `SUCCESS` or `FAILED`.
 */
export const DesignExportStatusEnum = {
    FAILED: 'FAILED',
    IN_PROGRESS: 'IN_PROGRESS',
    SUCCESS: 'SUCCESS'
} as const;

/**
 * The paper size of the export PDF file.
 */
export const ExportPageSizeEnum = {
    A4: 'A4',
    A3: 'A3',
    LETTER: 'LETTER',
    LEGAL: 'LEGAL'
} as const;

/**
 * The orientation and resolution of the exported video. Orientation is either `HORIZONTAL` or
 * `VERTICAL`, and resolution is one of `480P`, `720P`, `1080P` or `4K`.
 */
export const Mp4ExportQualityEnum = {
    HORIZONTAL_480P: 'HORIZONTAL_480P',
    HORIZONTAL_720P: 'HORIZONTAL_720P',
    HORIZONTAL_1080P: 'HORIZONTAL_1080P',
    HORIZONTAL_4K: 'HORIZONTAL_4K',
    VERTICAL_480P: 'VERTICAL_480P',
    VERTICAL_720P: 'VERTICAL_720P',
    VERTICAL_1080P: 'VERTICAL_1080P',
    VERTICAL_4K: 'VERTICAL_4K'
} as const;

/**
 * The access of the user, group, or team.
 * This can be one of the following:
 *
 * - `NONE`: They have no access to the folder.
 * - `VIEWER`: They have access to list or view the folder.
 * - `EDITOR`: They have access to:
 * - List or view the folder.
 * - Update folder metadata and content.
 * - `ADMIN`: They have access to:
 * - List or view the folder.
 * - Update folder metadata and content.
 * - Add, update, and remove the access of others.
 * - Move the folder or its subfolders if they have edit access to the source and
 * destination parent folders.
 * - Remove the folder or its subfolders, which moves the folder's contents to the owner’s
 * [**Projects**](https://www.canva.com/help/find-designs-and-folders/) (or `"root"`) folder.
 * - `OWNER`: In addition to `ADMIN` access, when they delete a folder, the items owned by the
 * user are sent to the [Trash](https://www.canva.com/help/deleted-designs/), and any other
 * content will be sent to the top level of its owner's
 * [**Projects**](https://www.canva.com/help/find-designs-and-folders/).
 *
 * The user who created the folder is the folder's `OWNER` and can't be
 * changed. The owner has _at least_ `ADMIN` access to all subfolders.
 */
export const FolderRoleEnum = {
    NONE: 'NONE',
    VIEWER: 'VIEWER',
    EDITOR: 'EDITOR',
    ADMIN: 'ADMIN',
    OWNER: 'OWNER'
} as const;

/**
 * The access of the user, group, or team.
 * This can be one of the following:
 *
 * - `NONE`: They have no access to the folder.
 * - `VIEWER`: They have access to list or view the folder.
 * - `EDITOR`: They have access to:
 * - List or view the folder.
 * - Update folder metadata and content.
 * - `ADMIN`: They have access to:
 * - List or view the folder.
 * - Update folder metadata and content.
 * - Add, update, and remove the access of others.
 * - Move the folder or its subfolders, if they have edit access to the parent folder.
 * - Remove the folder or its subfolders, which moves the folder's contents to the owner’s
 * [**Projects**](https://www.canva.com/help/find-designs-and-folders/) (or `"root"`) folder.
 */
export const UpdateFolderRoleInputEnum = {
    NONE: 'NONE',
    VIEWER: 'VIEWER',
    EDITOR: 'EDITOR',
    ADMIN: 'ADMIN'
} as const;

/**
 * The level of access granted to the Affinity Application.
 */
export const AffinityFeatureAccessLevelEnum = {
    NONE: 'NONE',
    FULL: 'FULL'
} as const;

/**
 * A short string indicating what failed. This field can be used to handle errors programmatically.
 *
 */
export const ErrorCodeEnum = {
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    INVALID_FIELD: 'INVALID_FIELD',
    INVALID_HEADER_VALUE: 'INVALID_HEADER_VALUE',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    NOT_FOUND: 'NOT_FOUND',
    BAD_REQUEST_BODY: 'BAD_REQUEST_BODY',
    BAD_HTTP_METHOD: 'BAD_HTTP_METHOD',
    BAD_REQUEST_PARAMS: 'BAD_REQUEST_PARAMS',
    BAD_QUERY_PARAMS: 'BAD_QUERY_PARAMS',
    ENDPOINT_NOT_FOUND: 'ENDPOINT_NOT_FOUND',
    UNSUPPORTED_VERSION: 'UNSUPPORTED_VERSION',
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
    REVOKED_ACCESS_TOKEN: 'REVOKED_ACCESS_TOKEN',
    MISSING_FIELD: 'MISSING_FIELD',
    MISSING_SCOPE: 'MISSING_SCOPE',
    INVALID_GRANT: 'invalid_grant',
    INVALID_REQUEST: 'invalid_request',
    INVALID_CLIENT: 'invalid_client',
    UNAUTHORIZED_CLIENT: 'unauthorized_client',
    UNSUPPORTED_GRANT_TYPE: 'unsupported_grant_type',
    INVALID_SCOPE: 'invalid_scope',
    INVALID_BASIC_HEADER: 'INVALID_BASIC_HEADER',
    INVALID_FILE_FORMAT: 'INVALID_FILE_FORMAT',
    QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
    UNSUPPORTED_CONTENT_TYPE: 'UNSUPPORTED_CONTENT_TYPE',
    REQUEST_TOO_LARGE: 'REQUEST_TOO_LARGE',
    FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
    ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
    MAX_LIMIT_REACHED: 'MAX_LIMIT_REACHED',
    PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
    PERMISSION_EXISTS: 'PERMISSION_EXISTS',
    UNAUTHORIZED_USER: 'UNAUTHORIZED_USER',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
    APP_NOT_FOUND: 'APP_NOT_FOUND',
    CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
    DOCTYPE_NOT_FOUND: 'DOCTYPE_NOT_FOUND',
    DESIGN_NOT_FOUND: 'DESIGN_NOT_FOUND',
    DESIGN_TYPE_NOT_FOUND: 'DESIGN_TYPE_NOT_FOUND',
    TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
    COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
    TOO_MANY_COMMENTS: 'TOO_MANY_COMMENTS',
    TOO_MANY_REPLIES: 'TOO_MANY_REPLIES',
    MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
    DESIGN_NOT_FILLABLE: 'DESIGN_NOT_FILLABLE',
    AUTOFILL_DATA_INVALID: 'AUTOFILL_DATA_INVALID',
    FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE'
} as const;

/**
 * The type of comment event.
 */
export const CommentEventTypeEnum = {
    COMMENT: 'COMMENT',
    REPLY: 'REPLY',
    MENTION: 'MENTION',
    ASSIGN: 'ASSIGN',
    RESOLVE: 'RESOLVE'
} as const;