// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  CreateAssetUploadJobData,
  CreateAssetUploadJobErrors,
  CreateAssetUploadJobResponses,
  CreateCommentData,
  CreateCommentErrors,
  CreateCommentResponses,
  CreateDesignAutofillJobData,
  CreateDesignAutofillJobErrors,
  CreateDesignAutofillJobResponses,
  CreateDesignData,
  CreateDesignErrors,
  CreateDesignExportJobData,
  CreateDesignExportJobErrors,
  CreateDesignExportJobResponses,
  CreateDesignImportJobData,
  CreateDesignImportJobErrors,
  CreateDesignImportJobResponses,
  CreateDesignMergeJobData,
  CreateDesignMergeJobErrors,
  CreateDesignMergeJobResponses,
  CreateDesignResizeJobData,
  CreateDesignResizeJobErrors,
  CreateDesignResizeJobResponses,
  CreateDesignResponses,
  CreateFolderData,
  CreateFolderErrors,
  CreateFolderResponses,
  CreatePrintPartnerDesignData,
  CreatePrintPartnerDesignErrors,
  CreatePrintPartnerDesignExportJobData,
  CreatePrintPartnerDesignExportJobErrors,
  CreatePrintPartnerDesignExportJobResponses,
  CreatePrintPartnerDesignResponses,
  CreateReplyData,
  CreateReplyErrors,
  CreateReplyResponses,
  CreateThreadData,
  CreateThreadErrors,
  CreateThreadResponses,
  CreateUrlAssetUploadJobData,
  CreateUrlAssetUploadJobErrors,
  CreateUrlAssetUploadJobResponses,
  CreateUrlImportJobData,
  CreateUrlImportJobErrors,
  CreateUrlImportJobResponses,
  DeleteAssetData,
  DeleteAssetErrors,
  DeleteAssetResponses,
  DeleteFolderData,
  DeleteFolderErrors,
  DeleteFolderResponses,
  ExchangeAccessTokenData,
  ExchangeAccessTokenErrors,
  ExchangeAccessTokenResponses,
  GetAppJwksData,
  GetAppJwksErrors,
  GetAppJwksResponses,
  GetAssetData,
  GetAssetErrors,
  GetAssetResponses,
  GetAssetUploadJobData,
  GetAssetUploadJobErrors,
  GetAssetUploadJobResponses,
  GetBrandTemplateData,
  GetBrandTemplateDatasetData,
  GetBrandTemplateDatasetErrors,
  GetBrandTemplateDatasetResponses,
  GetBrandTemplateErrors,
  GetBrandTemplateResponses,
  GetDesignAnalyticsData,
  GetDesignAnalyticsErrors,
  GetDesignAnalyticsLinksData,
  GetDesignAnalyticsLinksErrors,
  GetDesignAnalyticsLinksResponses,
  GetDesignAnalyticsPageViewsData,
  GetDesignAnalyticsPageViewsErrors,
  GetDesignAnalyticsPageViewsResponses,
  GetDesignAnalyticsResponses,
  GetDesignAnalyticsViewersData,
  GetDesignAnalyticsViewersErrors,
  GetDesignAnalyticsViewersResponses,
  GetDesignAnalyticsViewsOverTimeData,
  GetDesignAnalyticsViewsOverTimeErrors,
  GetDesignAnalyticsViewsOverTimeResponses,
  GetDesignAutofillJobData,
  GetDesignAutofillJobErrors,
  GetDesignAutofillJobResponses,
  GetDesignData,
  GetDesignDatasetData,
  GetDesignDatasetErrors,
  GetDesignDatasetResponses,
  GetDesignErrors,
  GetDesignExportFormatsData,
  GetDesignExportFormatsErrors,
  GetDesignExportFormatsResponses,
  GetDesignExportJobData,
  GetDesignExportJobErrors,
  GetDesignExportJobResponses,
  GetDesignImportJobData,
  GetDesignImportJobErrors,
  GetDesignImportJobResponses,
  GetDesignMergeJobData,
  GetDesignMergeJobErrors,
  GetDesignMergeJobResponses,
  GetDesignPagesData,
  GetDesignPagesErrors,
  GetDesignPagesResponses,
  GetDesignResizeJobData,
  GetDesignResizeJobErrors,
  GetDesignResizeJobResponses,
  GetDesignResponses,
  GetFolderData,
  GetFolderErrors,
  GetFolderResponses,
  GetOidcJwksData,
  GetOidcJwksErrors,
  GetOidcJwksResponses,
  GetPrintPartnerDesignData,
  GetPrintPartnerDesignErrors,
  GetPrintPartnerDesignResponses,
  GetReplyData,
  GetReplyErrors,
  GetReplyResponses,
  GetSigningPublicKeysData,
  GetSigningPublicKeysErrors,
  GetSigningPublicKeysResponses,
  GetThreadData,
  GetThreadErrors,
  GetThreadResponses,
  GetUrlAssetUploadJobData,
  GetUrlAssetUploadJobErrors,
  GetUrlAssetUploadJobResponses,
  GetUrlImportJobData,
  GetUrlImportJobErrors,
  GetUrlImportJobResponses,
  GetUserCapabilitiesData,
  GetUserCapabilitiesErrors,
  GetUserCapabilitiesResponses,
  GetUserProfileData,
  GetUserProfileErrors,
  GetUserProfileResponses,
  IntrospectTokenData,
  IntrospectTokenErrors,
  IntrospectTokenResponses,
  ListBrandTemplatesData,
  ListBrandTemplatesErrors,
  ListBrandTemplatesResponses,
  ListDesignsData,
  ListDesignsErrors,
  ListDesignsResponses,
  ListFolderItemsData,
  ListFolderItemsErrors,
  ListFolderItemsResponses,
  ListRepliesData,
  ListRepliesErrors,
  ListRepliesResponses,
  MoveFolderItemData,
  MoveFolderItemErrors,
  MoveFolderItemResponses,
  PublishBrandTemplateData,
  PublishBrandTemplateErrors,
  PublishBrandTemplateResponses,
  RevokeTokensData,
  RevokeTokensErrors,
  RevokeTokensResponses,
  UpdateAssetData,
  UpdateAssetErrors,
  UpdateAssetResponses,
  UpdateFolderData,
  UpdateFolderErrors,
  UpdateFolderResponses,
  UserInfoData,
  UserInfoErrors,
  UserInfoResponses,
  UsersMeData,
  UsersMeErrors,
  UsersMeResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class AnalyticsService {
  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * <Availability>
   * To use this API, your integration must act on behalf of a user who is a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.
   * </Availability>
   *
   * Gets the aggregated analytics for a design.
   *
   * The response includes total views, unique viewers, and view duration metrics.
   */
  public static getDesignAnalytics<ThrowOnError extends boolean = false>(
    options: Options<GetDesignAnalyticsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignAnalyticsResponses,
      GetDesignAnalyticsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/analytics",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * <Availability>
   * To use this API, your integration must act on behalf of a user who is a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.
   * </Availability>
   *
   * Lists viewers for a design, ordered by most recent view first.
   */
  public static getDesignAnalyticsViewers<ThrowOnError extends boolean = false>(
    options: Options<GetDesignAnalyticsViewersData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignAnalyticsViewersResponses,
      GetDesignAnalyticsViewersErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/analytics/viewers",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * <Availability>
   * To use this API, your integration must act on behalf of a user who is a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.
   * </Availability>
   *
   * Lists the view counts over time for a design.
   *
   * Each response item represents one time bucket.
   */
  public static getDesignAnalyticsViewsOverTime<
    ThrowOnError extends boolean = false,
  >(options: Options<GetDesignAnalyticsViewsOverTimeData, ThrowOnError>) {
    return (options.client ?? client).get<
      GetDesignAnalyticsViewsOverTimeResponses,
      GetDesignAnalyticsViewsOverTimeErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/analytics/views-over-time",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * <Availability>
   * To use this API, your integration must act on behalf of a user who is a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.
   * </Availability>
   *
   * Lists the page-level view duration data for a design.
   *
   * The request body can include page filters and pagination controls.
   */
  public static getDesignAnalyticsPageViews<
    ThrowOnError extends boolean = false,
  >(options: Options<GetDesignAnalyticsPageViewsData, ThrowOnError>) {
    return (options.client ?? client).post<
      GetDesignAnalyticsPageViewsResponses,
      GetDesignAnalyticsPageViewsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/analytics/page-views",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * <Availability>
   * To use this API, your integration must act on behalf of a user who is a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.
   * </Availability>
   *
   * Lists trackable links and their metrics for a design.
   */
  public static getDesignAnalyticsLinks<ThrowOnError extends boolean = false>(
    options: Options<GetDesignAnalyticsLinksData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignAnalyticsLinksResponses,
      GetDesignAnalyticsLinksErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/analytics/links",
      ...options,
    });
  }
}

export class AppService {
  /**
   * Returns the Json Web Key Set (public keys) of an app. These keys are used to
   * verify JWTs sent to app backends.
   */
  public static getAppJwks<ThrowOnError extends boolean = false>(
    options: Options<GetAppJwksData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetAppJwksResponses,
      GetAppJwksErrors,
      ThrowOnError
    >({ url: "/v1/apps/{appId}/jwks", ...options });
  }
}

export class AssetService {
  /**
   * You can delete an asset by specifying its `assetId`. This operation mirrors the behavior
   * in the Canva UI. Deleting an item moves it to the trash.
   * Deleting an asset doesn't remove it from designs that already use it.
   */
  public static deleteAsset<ThrowOnError extends boolean = false>(
    options: Options<DeleteAssetData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      DeleteAssetResponses,
      DeleteAssetErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/assets/{assetId}",
      ...options,
    });
  }

  /**
   * You can retrieve the metadata of an asset by specifying its `assetId`.
   */
  public static getAsset<ThrowOnError extends boolean = false>(
    options: Options<GetAssetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetAssetResponses,
      GetAssetErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/assets/{assetId}",
      ...options,
    });
  }

  /**
   * You can update the name and tags of an asset by specifying its `assetId`. Updating the tags
   * replaces all existing tags of the asset.
   */
  public static updateAsset<ThrowOnError extends boolean = false>(
    options: Options<UpdateAssetData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<
      UpdateAssetResponses,
      UpdateAssetErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/assets/{assetId}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to upload an asset to the user's content library. Supported file types for assets are listed in the [Assets API overview](https://www.canva.dev/docs/connect/api-reference/assets/).
   *
   * The request format for this endpoint is an `application/octet-stream` body of bytes. Attach
   * information about the upload using an `Asset-Upload-Metadata` header.
   *
   *
   * <Note>
   *
   * For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of asset upload jobs created with this API using the [Get asset upload job API](https://www.canva.dev/docs/connect/api-reference/assets/get-asset-upload-job/).
   *
   * </Note>
   */
  public static createAssetUploadJob<ThrowOnError extends boolean = false>(
    options: Options<CreateAssetUploadJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateAssetUploadJobResponses,
      CreateAssetUploadJobErrors,
      ThrowOnError
    >({
      bodySerializer: null,
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/asset-uploads",
      ...options,
      headers: {
        "Content-Type": "application/octet-stream",
        ...options.headers,
      },
    });
  }

  /**
   * Get the result of an asset upload job that was created using the [Create asset upload job API](https://www.canva.dev/docs/connect/api-reference/assets/create-asset-upload-job/).
   *
   * You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
   */
  public static getAssetUploadJob<ThrowOnError extends boolean = false>(
    options: Options<GetAssetUploadJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetAssetUploadJobResponses,
      GetAssetUploadJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/asset-uploads/{jobId}",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to upload an asset from a URL to the user's content library. Supported file types for assets are listed in the [Assets API overview](https://www.canva.dev/docs/connect/api-reference/assets/).
   *
   * <Note>
   * Uploading a video asset from a URL is limited to a maximum 100MB file size. For importing larger video files, use the [Create asset upload job API](https://www.canva.dev/docs/connect/api-reference/assets/create-asset-upload-job/).
   * </Note>
   *
   * <Note>
   * For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of asset upload jobs created with this API using the [Get asset upload job via URL API](https://www.canva.dev/docs/connect/api-reference/assets/get-url-asset-upload-job/).
   * </Note>
   */
  public static createUrlAssetUploadJob<ThrowOnError extends boolean = false>(
    options: Options<CreateUrlAssetUploadJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateUrlAssetUploadJobResponses,
      CreateUrlAssetUploadJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/url-asset-uploads",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * Get the result of an asset upload job that was created using the [Create asset upload job via URL API](https://www.canva.dev/docs/connect/api-reference/assets/create-url-asset-upload-job/).
   *
   * You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
   */
  public static getUrlAssetUploadJob<ThrowOnError extends boolean = false>(
    options: Options<GetUrlAssetUploadJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetUrlAssetUploadJobResponses,
      GetUrlAssetUploadJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/url-asset-uploads/{jobId}",
      ...options,
    });
  }
}

export class AutofillService {
  /**
   * WARNING: Brand templates were migrated to use a new ID format in September 2025. If your integration stores brand template IDs, you'll need to migrate to use the new IDs. Old brand template IDs will continue to be accepted for 6 months to give you time to migrate to the new IDs.
   *
   * <Availability>
   * To use this API, your integration must act on behalf of a user who is a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.
   *
   * Users on Canva paid plans have access to a limited trial while your integration is under development. For more information, see [Trial quotas](https://www.canva.dev/docs/connect/api-requests-responses/#trial-quotas).
   * </Availability>
   *
   * Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to autofill a new Canva design using input data. Use the `type` field to choose the source of the design:
   *
   * - `create_from_brand_template`: autofill a new design from a brand template. If `type` isn't specified in the request, the request type is assumed to be `create_from_brand_template`. To get a list of input data fields for a brand template, use the [Get brand template dataset API](https://www.canva.dev/docs/connect/api-reference/brand-templates/get-brand-template-dataset/).
   * - `create_from_design`: autofill a new design from an existing design that contains autofill data fields. To get the input data fields for an existing design, use the [Get design dataset
   * API](https://www.canva.dev/docs/connect/api-reference/designs/get-design-dataset/).
   *
   * WARNING: Creating an autofilled design from an existing design is a [preview feature](https://www.canva.dev/docs/connect/#preview-apis). There might be unannounced breaking changes to this feature which won't produce a new API version.
   *
   * Available data field types to autofill include:
   *
   * - Images (which you can autofill with an image or a video asset)
   * - Text
   * - Charts
   * - Sheets
   *
   * WARNING: Chart and sheet data fields and autofilling a video are [preview features](https://www.canva.dev/docs/connect/#preview-apis). There might be unannounced breaking changes to these features which won't produce a new API version.
   *
   * NOTE: For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of autofill jobs created with this API using the [Get design autofill job API](https://www.canva.dev/docs/connect/api-reference/autofills/get-design-autofill-job/).
   */
  public static createDesignAutofillJob<ThrowOnError extends boolean = false>(
    options?: Options<CreateDesignAutofillJobData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      CreateDesignAutofillJobResponses,
      CreateDesignAutofillJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/autofills",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * <Availability>
   * To use this API, your integration must act on behalf of a user who is a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.
   *
   * Users on Canva paid plans have access to a limited trial while your integration is under development. For more information, see [Trial quotas](https://www.canva.dev/docs/connect/api-requests-responses/#trial-quotas).
   * </Availability>
   *
   * Get the result of a design autofill job that was created using the [Create design autofill job
   * API](https://www.canva.dev/docs/connect/api-reference/autofills/create-design-autofill-job/).
   *
   * You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
   */
  public static getDesignAutofillJob<ThrowOnError extends boolean = false>(
    options: Options<GetDesignAutofillJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignAutofillJobResponses,
      GetDesignAutofillJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/autofills/{jobId}",
      ...options,
    });
  }
}

export class BrandTemplateService {
  /**
   * WARNING: Brand templates were migrated to use a new ID format in September 2025. If your integration stores brand template IDs, you'll need to migrate to use the new IDs. Old brand template IDs will continue to be accepted for 6 months to give you time to migrate to the new IDs.
   *
   * AVAILABILITY: To use this API, your integration must act on behalf of a user that's on a Canva plan with access to brand templates (such as Canva Pro, Canva Teams, or Canva Enterprise).
   *
   * Get a list of the [brand templates](https://www.canva.com/help/publish-team-template/) the user has access to.
   */
  public static listBrandTemplates<ThrowOnError extends boolean = false>(
    options?: Options<ListBrandTemplatesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ListBrandTemplatesResponses,
      ListBrandTemplatesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/brand-templates",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * AVAILABILITY: To use this API, your integration must act on behalf of a user that's on a Canva plan with access to brand templates (such as Canva Pro, Canva Teams, or Canva Enterprise). Additionally, the user must have one of the following [roles](https://www.canva.com/help/roles-and-permissions/): Team admin, Brand designer, Organization admin, or Organization designer.
   *
   * Publishes a design as a [brand template](https://www.canva.com/help/publish-team-template/). Brand templates are design templates that can be shared across a team for consistent content creation.
   *
   * This API supports two workflows:
   *
   * - **Initial publish**: If the design is not linked to an existing brand template, a new brand template is created.
   * - **Republish**: If the design is a draft of an existing brand template (created by editing an existing template), the existing template is updated with the changes.
   *
   * The API returns the published brand template immediately.
   *
   * <Note>
   * The `thumbnail` field might be `null` immediately after publishing, as thumbnails are generated asynchronously. You can use the [Get brand template API](https://www.canva.dev/docs/connect/api-reference/brand-templates/get-brand-template/) to retrieve the thumbnail once it's ready. The brand template's `view_url` and `create_url` are available immediately.
   * </Note>
   */
  public static publishBrandTemplate<ThrowOnError extends boolean = false>(
    options: Options<PublishBrandTemplateData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      PublishBrandTemplateResponses,
      PublishBrandTemplateErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/brand-templates",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * WARNING: Brand templates were migrated to use a new ID format in September 2025. If your integration stores brand template IDs, you'll need to migrate to use the new IDs. Old brand template IDs will continue to be accepted for 6 months to give you time to migrate to the new IDs.
   *
   * AVAILABILITY: To use this API, your integration must act on behalf of a user that's on a Canva plan with access to brand templates (such as Canva Pro, Canva Teams, or Canva Enterprise).
   *
   * Retrieves the metadata for a brand template.
   */
  public static getBrandTemplate<ThrowOnError extends boolean = false>(
    options: Options<GetBrandTemplateData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetBrandTemplateResponses,
      GetBrandTemplateErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/brand-templates/{brandTemplateId}",
      ...options,
    });
  }

  /**
   * WARNING: Brand templates were migrated to use a new ID format in September 2025. If your integration stores brand template IDs, you'll need to migrate to use the new IDs. Old brand template IDs will continue to be accepted for 6 months to give you time to migrate to the new IDs.
   *
   * AVAILABILITY: To use this API, your integration must act on behalf of a user that's on a Canva plan with access to brand templates (such as Canva Pro, Canva Teams, or Canva Enterprise).
   *
   * Gets the dataset definition of a brand template. If the brand
   * template contains autofill data fields, this API returns an object with the data field
   * names and the type of data they accept.
   *
   * <Note>
   *
   * To get the dataset definition of a design, use the
   * [Get design dataset API](https://www.canva.dev/docs/connect/api-reference/designs/get-design-dataset/).
   *
   * </Note>
   *
   * Available data field types include:
   *
   * - Images (which you can autofill with an image or a video asset)
   * - Text
   * - Charts
   *
   * You can autofill a brand template using the [Create a design autofill job
   * API](https://www.canva.dev/docs/connect/api-reference/autofills/create-design-autofill-job/).
   *
   * WARNING: Chart data fields and autofilling a video are [preview features](https://www.canva.dev/docs/connect/#preview-apis). There might be unannounced breaking changes to these features which won't produce a new API version.
   */
  public static getBrandTemplateDataset<ThrowOnError extends boolean = false>(
    options: Options<GetBrandTemplateDatasetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetBrandTemplateDatasetResponses,
      GetBrandTemplateDatasetErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/brand-templates/{brandTemplateId}/dataset",
      ...options,
    });
  }
}

export class CommentService {
  /**
   * <Warning>
   *
   * This preview API is deprecated. You should use the [Create thread](https://www.canva.dev/docs/connect/api-reference/comments/create-thread/) API instead.
   *
   * </Warning>
   *
   * Create a new top-level comment on a design.
   * For information on comments and how they're used in the Canva UI, see the
   * [Canva Help Center](https://www.canva.com/help/comments/). A design can have a maximum
   * of 1000 comments.
   *
   * @deprecated
   */
  public static createComment<ThrowOnError extends boolean = false>(
    options: Options<CreateCommentData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateCommentResponses,
      CreateCommentErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/comments",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * <Warning>
   * This API is currently provided as a preview. Be aware of the following:
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   * </Warning>
   *
   * Retrieves a list of replies for a comment or suggestion thread on a design.
   *
   * For information on comments and how they're used in the Canva UI, see the
   * [Canva Help Center](https://www.canva.com/help/comments/).
   */
  public static listReplies<ThrowOnError extends boolean = false>(
    options: Options<ListRepliesData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      ListRepliesResponses,
      ListRepliesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/comments/{threadId}/replies",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * Creates a reply to a comment or suggestion thread on a design.
   * To reply to an existing thread, you must provide the ID of the thread
   * which is returned when a thread is created, or from the `thread_id` value
   * of an existing reply in the thread. Each thread can
   * have a maximum of 100 replies created for it.
   *
   * For information on comments and how they're used in the Canva UI, see the
   * [Canva Help Center](https://www.canva.com/help/comments/).
   */
  public static createReply<ThrowOnError extends boolean = false>(
    options: Options<CreateReplyData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateReplyResponses,
      CreateReplyErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/comments/{threadId}/replies",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * Gets a comment or suggestion thread on a design.
   * To retrieve a reply to a comment thread, use the [Get reply](https://www.canva.dev/docs/connect/api-reference/comments/get-reply/) API.
   * For information on comments and how they're used in the Canva UI, see the
   * [Canva Help Center](https://www.canva.com/help/comments/).
   */
  public static getThread<ThrowOnError extends boolean = false>(
    options: Options<GetThreadData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetThreadResponses,
      GetThreadErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/comments/{threadId}",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * Gets a reply to a comment or suggestion thread on a design.
   * For information on comments and how they're used in the Canva UI, see the
   * [Canva Help Center](https://www.canva.com/help/comments/).
   */
  public static getReply<ThrowOnError extends boolean = false>(
    options: Options<GetReplyData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetReplyResponses,
      GetReplyErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/comments/{threadId}/replies/{replyId}",
      ...options,
    });
  }

  /**
   * <Warning>
   * This API is currently provided as a preview. Be aware of the following:
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   * </Warning>
   *
   * Creates a new comment thread on a design.
   * For information on comments and how they're used in the Canva UI, see the
   * [Canva Help Center](https://www.canva.com/help/comments/).
   */
  public static createThread<ThrowOnError extends boolean = false>(
    options: Options<CreateThreadData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateThreadResponses,
      CreateThreadErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/comments",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class ConnectService {
  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * The Keys API (`connect/keys`) is a security measure you can use to verify the authenticity
   * of webhooks you receive from Canva Connect. The Keys API returns a
   * [JSON Web Key (JWK)](https://www.rfc-editor.org/rfc/rfc7517#section-2), which you can use to
   * decrypt the webhook signature and verify it came from Canva and not a potentially malicious
   * actor. This helps to protect your systems from
   * [Replay attacks](https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/).
   *
   * The keys returned by the Keys API can rotate. We recommend you cache the keys you receive
   * from this API where possible, and only access this API when you receive a webhook signed
   * with an unrecognized key. This allows you to verify webhooks quicker than accessing this API
   * every time you receive a webhook.
   */
  public static getSigningPublicKeys<ThrowOnError extends boolean = false>(
    options?: Options<GetSigningPublicKeysData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetSigningPublicKeysResponses,
      GetSigningPublicKeysErrors,
      ThrowOnError
    >({ url: "/v1/connect/keys", ...options });
  }
}

export class DesignService {
  /**
   * Lists metadata for all the designs in a Canva user's
   * [projects](https://www.canva.com/help/find-designs-and-folders/). You can also:
   *
   * - Use search terms to filter the listed designs.
   * - Show designs either created by, or shared with the user.
   * - Sort the results.
   */
  public static listDesigns<ThrowOnError extends boolean = false>(
    options?: Options<ListDesignsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ListDesignsResponses,
      ListDesignsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs",
      ...options,
    });
  }

  /**
   * Creates a new Canva design. To create a new design, you can:
   *
   * - Use a preset design type.
   * - Set height and width dimensions for a custom design.
   *
   * NOTE: Custom designs can have a maximum area of 25,000,000 pixels squared (for example, 5000 × 5000 pixels). Each dimension can be between 40 and 8000 pixels, but the total area must stay within this limit.
   * - Create a copy of an existing design (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).
   * - Create a new design from a brand template (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).
   *
   * For preset and custom designs, you can also provide the `asset_id` of an asset in the user's [projects](https://www.canva.com/help/find-designs-and-folders/) to add to the new design. Currently, this only supports image assets. To list the assets in a folder in the user's projects, use the [List folder items API](https://www.canva.dev/docs/connect/api-reference/folders/list-folder-items/).
   *
   * NOTE: Blank designs created with this API are automatically deleted if they're not edited within 7 days. These blank designs bypass the user's Canva trash and are permanently deleted.
   */
  public static createDesign<ThrowOnError extends boolean = false>(
    options?: Options<CreateDesignData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      CreateDesignResponses,
      CreateDesignErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Gets the metadata for a design. This includes owner information, URLs for editing and viewing, and thumbnail information.
   */
  public static getDesign<ThrowOnError extends boolean = false>(
    options: Options<GetDesignData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignResponses,
      GetDesignErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * Lists metadata for pages in a design, such as page-specific thumbnails.
   *
   * For the specified design, you can provide `offset` and `limit` values to specify the range of pages to return.
   *
   * NOTE: Some design types don't have pages (for example, Canva docs).
   */
  public static getDesignPages<ThrowOnError extends boolean = false>(
    options: Options<GetDesignPagesData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignPagesResponses,
      GetDesignPagesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/pages",
      ...options,
    });
  }

  /**
   * Lists the available file formats for [exporting a design](https://www.canva.dev/docs/connect/api-reference/exports/create-design-export-job/).
   *
   * <Note>
   * The available export formats depend on the design type and the types of pages in the design.
   * Each format includes the page numbers that support it. If a format is supported by every page in the design, its `page_numbers` are omitted.
   * </Note>
   */
  public static getDesignExportFormats<ThrowOnError extends boolean = false>(
    options: Options<GetDesignExportFormatsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignExportFormatsResponses,
      GetDesignExportFormatsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/export-formats",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * Gets the dataset definition of a design. If the design contains autofill data fields, this API
   * returns an object with the data field names and the type of data they accept.
   *
   * <Note>
   *
   * To get the dataset definition of a brand template, use the
   * [Get brand template dataset API](https://www.canva.dev/docs/connect/api-reference/brand-templates/get-brand-template-dataset/).
   *
   * </Note>
   *
   * Available data field types include:
   *
   * - Images (which you can autofill with an image or a video asset)
   * - Text
   * - Charts
   *
   * Use the returned field names and types to build the `data` payload for the
   * [Create a design autofill job API](https://www.canva.dev/docs/connect/api-reference/autofills/create-design-autofill-job/)
   * with `type: create_from_design`.
   *
   * WARNING: Chart data fields and autofilling a video are [preview features](https://www.canva.dev/docs/connect/#preview-apis). There might be unannounced breaking changes to these features which won't produce a new API version.
   */
  public static getDesignDataset<ThrowOnError extends boolean = false>(
    options: Options<GetDesignDatasetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignDatasetResponses,
      GetDesignDatasetErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/designs/{designId}/dataset",
      ...options,
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * AVAILABILITY: This API is only available to Print Partners.
   *
   * Creates a new Canva design using a Print Partner product ID.
   *
   * Print partner proofing information (such as bleed and page constraints) can optionally be provided in the request. The design URLs that are returned include this information, which Canva applies in the editor when opening the design.
   *
   * NOTE: Blank designs created with this API are automatically deleted if they're not edited within 7 days. These blank designs bypass the user's Canva trash and are permanently deleted.
   */
  public static createPrintPartnerDesign<ThrowOnError extends boolean = false>(
    options?: Options<CreatePrintPartnerDesignData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      CreatePrintPartnerDesignResponses,
      CreatePrintPartnerDesignErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/print-partner/designs",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * AVAILABILITY: This API is only available to Print Partners.
   *
   * Gets the metadata for a design. This includes owner information, URLs for editing and viewing, and thumbnail information.
   *
   * Print partner proofing information (such as bleed and page constraints) isn't stored on Canva, so you can optionally provide it in the request. The design URLs that are returned include this information, which Canva applies in the editor when opening the design.
   */
  public static getPrintPartnerDesign<ThrowOnError extends boolean = false>(
    options: Options<GetPrintPartnerDesignData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetPrintPartnerDesignResponses,
      GetPrintPartnerDesignErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/print-partner/designs/{designId}",
      ...options,
    });
  }
}

export class DesignImportService {
  /**
   * Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to import an external file as a new design in Canva.
   *
   * The request format for this endpoint has an `application/octet-stream` body of bytes,
   * and the information about the import is provided using an `Import-Metadata` header.
   *
   * Supported file types for imports are listed in [Design imports overview](https://www.canva.dev/docs/connect/api-reference/design-imports/#supported-file-types).
   *
   * <Note>
   *
   * For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of design import jobs created with this API using the [Get design import job API](https://www.canva.dev/docs/connect/api-reference/design-imports/get-design-import-job/).
   *
   * </Note>
   */
  public static createDesignImportJob<ThrowOnError extends boolean = false>(
    options: Options<CreateDesignImportJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateDesignImportJobResponses,
      CreateDesignImportJobErrors,
      ThrowOnError
    >({
      bodySerializer: null,
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/imports",
      ...options,
      headers: {
        "Content-Type": "application/octet-stream",
        ...options.headers,
      },
    });
  }

  /**
   * Gets the result of a design import job created using the [Create design import job API](https://www.canva.dev/docs/connect/api-reference/design-imports/create-design-import-job/).
   *
   * You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
   */
  public static getDesignImportJob<ThrowOnError extends boolean = false>(
    options: Options<GetDesignImportJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignImportJobResponses,
      GetDesignImportJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/imports/{jobId}",
      ...options,
    });
  }

  /**
   * Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to import an external file from a URL as a new design in Canva.
   *
   * Supported file types for imports are listed in [Design imports overview](https://www.canva.dev/docs/connect/api-reference/design-imports/#supported-file-types).
   *
   * <Note>
   *
   * For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of design import jobs created with this API using the [Get URL import job API](https://www.canva.dev/docs/connect/api-reference/design-imports/get-url-import-job/).
   *
   * </Note>
   */
  public static createUrlImportJob<ThrowOnError extends boolean = false>(
    options: Options<CreateUrlImportJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateUrlImportJobResponses,
      CreateUrlImportJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/url-imports",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Gets the result of a URL import job created using the [Create URL import job API](https://www.canva.dev/docs/connect/api-reference/design-imports/create-url-import-job/).
   *
   * You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
   */
  public static getUrlImportJob<ThrowOnError extends boolean = false>(
    options: Options<GetUrlImportJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetUrlImportJobResponses,
      GetUrlImportJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/url-imports/{jobId}",
      ...options,
    });
  }
}

export class ExportService {
  /**
   * Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to export a file from Canva. Once the exported file is generated, you can download
   * it using the URL(s) provided. The download URLs are only valid for 24 hours.
   *
   * The request requires the design ID and the exported file format type.
   *
   * Supported file formats (and export file type values): JPG (`jpg`), PNG (`png`), GIF (`gif`), Microsoft PowerPoint (`pptx`), MP4 (`mp4`), PDF (`pdf`), CSV (`csv`), HTML bundle (`html_bundle`), and standalone HTML (`html_standalone`).
   *
   * <Note>
   *
   * This endpoint has the following additional rate limits:
   *
   * - **Integration throttle:** Each integration can export a maximum of 750 times per 5-minute window, and 5,000 times per 24-hour window.
   * - **Document throttle:** Each document can be exported a maximum of 75 times per 5-minute window.
   * - **User throttle:** Each user can export a maximum of 75 times per 5-minute window, and 500 times per 24-hour window.
   *
   * </Note>
   * <Note>
   *
   * For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of export jobs created with this API using the [Get design export job API](https://www.canva.dev/docs/connect/api-reference/exports/get-design-export-job/).
   *
   * </Note>
   */
  public static createDesignExportJob<ThrowOnError extends boolean = false>(
    options?: Options<CreateDesignExportJobData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      CreateDesignExportJobResponses,
      CreateDesignExportJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/exports",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * AVAILABILITY: This API is only available to Print Partners.
   *
   * Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to export a Print Partner file from Canva. Once the exported file is generated, you can download
   * it using the URL(s) provided. The download URLs are only valid for 24 hours.
   * The request requires the design ID and exports a file as a print-quality PDF.
   *
   * <Note>
   * For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of export jobs created with this API using the [Get design export job API](https://www.canva.dev/docs/connect/api-reference/exports/get-design-export-job/).
   * </Note>
   */
  public static createPrintPartnerDesignExportJob<
    ThrowOnError extends boolean = false,
  >(options?: Options<CreatePrintPartnerDesignExportJobData, ThrowOnError>) {
    return (options?.client ?? client).post<
      CreatePrintPartnerDesignExportJobResponses,
      CreatePrintPartnerDesignExportJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/print-partner/exports",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Gets the result of a design export job that was created using the [Create design export job API](https://www.canva.dev/docs/connect/api-reference/exports/create-design-export-job/).
   *
   * If the job is successful, the response includes an array
   * of download URLs. Depending on the design type and export format, there is a download URL for each page in the design. The download URLs are only valid for 24 hours.
   *
   * You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
   */
  public static getDesignExportJob<ThrowOnError extends boolean = false>(
    options: Options<GetDesignExportJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignExportJobResponses,
      GetDesignExportJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/exports/{exportId}",
      ...options,
    });
  }
}

export class FolderService {
  /**
   * Deletes a folder with the specified `folderID`.
   * Deleting a folder moves the user's content in the folder to the
   * [Trash](https://www.canva.com/help/deleted-designs/) and content owned by
   * other users is moved to the top level of the owner's
   * [projects](https://www.canva.com/help/find-designs-and-folders/).
   */
  public static deleteFolder<ThrowOnError extends boolean = false>(
    options: Options<DeleteFolderData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      DeleteFolderResponses,
      DeleteFolderErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/folders/{folderId}",
      ...options,
    });
  }

  /**
   * Gets the name and other details of a folder using a folder's `folderID`.
   */
  public static getFolder<ThrowOnError extends boolean = false>(
    options: Options<GetFolderData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetFolderResponses,
      GetFolderErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/folders/{folderId}",
      ...options,
    });
  }

  /**
   * Updates a folder's details using its `folderID`.
   * Currently, you can only update a folder's name.
   */
  public static updateFolder<ThrowOnError extends boolean = false>(
    options: Options<UpdateFolderData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<
      UpdateFolderResponses,
      UpdateFolderErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/folders/{folderId}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Lists the items in a folder, including each item's `type`.
   *
   * Folders can contain:
   *
   * - Other folders.
   * - Designs, such as Instagram posts, Presentations, and Documents ([Canva Docs](https://www.canva.com/create/documents/)).
   * - Image assets.
   * - Brand templates. To include `brand_template` items in the response, you must explicitly specify it in the `item_types` parameter.
   *
   * AVAILABILITY: Brand template items are only returned for users on a Canva plan with access to brand templates (such as Canva Pro, Canva Teams, or Canva Enterprise). For more information, see [Brand templates](https://www.canva.dev/docs/connect/api-reference/brand-templates/).
   *
   * Currently, video assets are not returned in the response.
   */
  public static listFolderItems<ThrowOnError extends boolean = false>(
    options: Options<ListFolderItemsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      ListFolderItemsResponses,
      ListFolderItemsErrors,
      ThrowOnError
    >({
      querySerializer: {
        parameters: { item_types: { array: { explode: false } } },
      },
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/folders/{folderId}/items",
      ...options,
    });
  }

  /**
   * Moves an item to another folder. You must specify the folder ID of the destination folder, as well as the ID of the item you want to move.
   *
   * NOTE: In some situations, a single item can exist in multiple folders. If you attempt to move an item that exists in multiple folders, the API returns an `item_in_multiple_folders` error. In this case, you must use the Canva UI to move the item to another folder.
   */
  public static moveFolderItem<ThrowOnError extends boolean = false>(
    options?: Options<MoveFolderItemData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      MoveFolderItemResponses,
      MoveFolderItemErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/folders/move",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Creates a folder in one of the following locations:
   *
   * - The top level of a Canva user's [projects](https://www.canva.com/help/find-designs-and-folders/) (using the ID `root`),
   * - The user's Uploads folder (using the ID `uploads`),
   * - Another folder (using the parent folder's ID).
   *
   * When a folder is successfully created, the
   * endpoint returns its folder ID, along with other information.
   */
  public static createFolder<ThrowOnError extends boolean = false>(
    options: Options<CreateFolderData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateFolderResponses,
      CreateFolderErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/folders",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class MergeService {
  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to merge design pages by applying page operations (such as insert, move, or delete) to produce a new design or modify an existing one.
   *
   * When the job completes successfully, the job result includes metadata for the created or updated design.
   *
   * <Note>
   *
   * At this stage, only a single operation per request is supported by default, and passing multiple operations will fail. Contact Canva to enable multi-operation mode for your integration.
   *
   * </Note>
   *
   * <Note>
   *
   * For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of jobs created with this API using the [Get design merge job API](https://www.canva.dev/docs/connect/api-reference/merges/get-design-merge-job/).
   *
   * </Note>
   */
  public static createDesignMergeJob<ThrowOnError extends boolean = false>(
    options: Options<CreateDesignMergeJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateDesignMergeJobResponses,
      CreateDesignMergeJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/merges",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * <Warning>
   *
   * This API is currently provided as a preview. Be aware of the following:
   *
   * - There might be unannounced breaking changes.
   * - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
   * - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.
   *
   * </Warning>
   *
   * Gets the result of a design merge job that was created using the [Create design merge job API](https://www.canva.dev/docs/connect/api-reference/merges/create-design-merge-job/).
   *
   * If the job is successful, the response includes the job status and a `result` object with metadata for the created or updated design.
   *
   * You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
   */
  public static getDesignMergeJob<ThrowOnError extends boolean = false>(
    options: Options<GetDesignMergeJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignMergeJobResponses,
      GetDesignMergeJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/merges/{jobId}",
      ...options,
    });
  }
}

export class OauthService {
  /**
   * This endpoint implements the OAuth 2.0 `token` endpoint, as part of the Authorization Code flow with Proof Key for Code Exchange (PKCE). For more information, see [Authentication](https://www.canva.dev/docs/connect/authentication/).
   *
   * To generate an access token, you must provide one of the following:
   *
   * - An authorization code
   * - A refresh token
   *
   * Generating a token using either an authorization code or a refresh token allows your integration to act on behalf of a user. You must first [obtain user authorization and get an authorization code](https://www.canva.dev/docs/connect/authentication/#obtain-user-authorization).
   *
   * Access tokens may be up to 4 KB in size, and are only valid for a specified period of time. The expiry time (currently 4 hours) is shown in the endpoint response and is subject to change.
   *
   * **Endpoint authentication**
   *
   * Requests to this endpoint require authentication with your client ID and client secret, using _one_ of the following methods:
   *
   * - **Basic access authentication** (Recommended): For [basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication), the `{credentials}` string must be a Base64 encoded value of `{client id}:{client secret}`.
   * - **Body parameters**: Provide your integration's credentials using the `client_id` and `client_secret` body parameters.
   *
   * This endpoint can't be called from a user's web-browser client because it uses client authentication with client secrets. Requests must come from your integration's backend, otherwise they'll be blocked by Canva's [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policy.
   *
   * **Generate an access token using an authorization code**
   *
   * To generate an access token with an authorization code, you must:
   *
   * - Set `grant_type` to `authorization_code`.
   * - Provide the `code_verifier` value that you generated when creating the user authorization URL.
   * - Provide the authorization code you received after the user authorized the integration.
   *
   * **Generate an access token using a refresh token**
   *
   * Using the `refresh_token` value from a previous user token request, you can get a new access token with the same or smaller scope as the previous one, but with a refreshed expiry time. You will also receive a new refresh token that you can use to refresh the access token again.
   *
   * To refresh an existing access token, you must:
   *
   * - Set `grant_type` to `refresh_token`.
   * - Provide the `refresh_token` from a previous token request.
   */
  public static exchangeAccessToken<ThrowOnError extends boolean = false>(
    options: Options<ExchangeAccessTokenData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      ExchangeAccessTokenResponses,
      ExchangeAccessTokenErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      security: [{ scheme: "basic", type: "http" }],
      url: "/v1/oauth/token",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    });
  }

  /**
   * Introspect an access token to see whether it is valid and active. You can also verify some token properties, such as its claims, scopes, and validity times.
   *
   * Requests to this endpoint require authentication with your client ID and client secret, using _one_ of the following methods:
   *
   * - **Basic access authentication** (Recommended): For [basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication), the `{credentials}` string must be a Base64 encoded value of `{client id}:{client secret}`.
   * - **Body parameters**: Provide your integration's credentials using the `client_id` and `client_secret` body parameters.
   *
   * This endpoint can't be called from a user's web-browser client because it uses client authentication with client secrets. Requests must come from your integration's backend, otherwise they'll be blocked by Canva's [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policy.
   */
  public static introspectToken<ThrowOnError extends boolean = false>(
    options: Options<IntrospectTokenData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      IntrospectTokenResponses,
      IntrospectTokenErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      security: [{ scheme: "basic", type: "http" }],
      url: "/v1/oauth/introspect",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    });
  }

  /**
   * Revoke an access token or a refresh token.
   *
   * If you revoke a _refresh token_, be aware that:
   *
   * - The refresh token's lineage is also revoked. This means that access tokens created from that refresh token are also revoked.
   * - The user's consent for your integration is also revoked. This means that the user must go through the OAuth process again to use your integration.
   *
   * Requests to this endpoint require authentication with your client ID and client secret, using _one_ of the following methods:
   *
   * - **Basic access authentication** (Recommended): For [basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication), the `{credentials}` string must be a Base64 encoded value of `{client id}:{client secret}`.
   * - **Body parameters**: Provide your integration's credentials using the `client_id` and `client_secret` body parameters.
   *
   * This endpoint can't be called from a user's web-browser client because it uses client authentication with client secrets. Requests must come from your integration's backend, otherwise they'll be blocked by Canva's [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policy.
   */
  public static revokeTokens<ThrowOnError extends boolean = false>(
    options: Options<RevokeTokensData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      RevokeTokensResponses,
      RevokeTokensErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      security: [{ scheme: "basic", type: "http" }],
      url: "/v1/oauth/revoke",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    });
  }
}

export class OidcService {
  /**
   * Gets the JSON Web Key Set (public keys) for OIDC. These keys are used to verify JWTs in OpenID Connect flows.
   */
  public static getOidcJwks<ThrowOnError extends boolean = false>(
    options?: Options<GetOidcJwksData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetOidcJwksResponses,
      GetOidcJwksErrors,
      ThrowOnError
    >({ url: "/v1/oidc/jwks", ...options });
  }

  /**
   * Fetches the current UserInfo claims for the authorized user. This is the same fields
   * returned by a id_token returns during authorization.
   *
   * The claims returned depend on the granted scopes: `profile` claims (`name`, `given_name`,
   * `family_name`) are only returned when the `profile` scope is granted, and `email` claims
   * (`email`, `email_verified`) are only returned when the `email` scope is granted. The
   * `openid` scope is always required.
   */
  public static userInfo<ThrowOnError extends boolean = false>(
    options?: Options<UserInfoData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      UserInfoResponses,
      UserInfoErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/oidc/userinfo",
      ...options,
    });
  }
}

export class ResizeService {
  /**
   * <Availability>
   *
   * To use this API, your integration must act on behalf of a user that's on a Canva plan with premium features (such as Canva Pro).
   *
   * Users on the Canva Free plan have access to a limited trial. For more information, see [Trial quotas](https://www.canva.dev/docs/connect/api-requests-responses/#trial-quotas).
   *
   * </Availability>
   *
   * Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints)
   * to create a resized copy of a design. The new resized design is
   * added to the top level of the user's
   * [projects](https://www.canva.com/help/find-designs-and-folders/) (`root` folder).
   *
   * To resize a design into a new design, you can either:
   *
   * - Use a preset design type.
   * - Set height and width dimensions for a custom design.
   *
   * Note the following behaviors and restrictions when resizing designs:
   * - Designs can be resized to a maximum area of 25,000,000 pixels squared.
   * - Resizing designs using the Connect API always creates a new design. In-place resizing is currently not available in the Connect API, but can be done in the Canva UI.
   * - Resizing a multi-page design results in all pages of the design being resized. Resizing a section of a design is only available in the Canva UI.
   * - [Canva docs](https://www.canva.com/create/documents/) and [emails](https://www.canva.com/emails/) can't be resized, and other design types can't be resized to a Canva doc or email.
   * - Canva Code designs can't be resized, and other design types can't be resized to a Canva Code design.
   *
   * <Note>
   * For more information on the workflow for using asynchronous jobs,
   * see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
   * You can check the status and get the results of resize jobs created with this API using the
   * [Get design resize job API](https://www.canva.dev/docs/connect/api-reference/resizes/get-design-resize-job/).
   * </Note>
   */
  public static createDesignResizeJob<ThrowOnError extends boolean = false>(
    options?: Options<CreateDesignResizeJobData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      CreateDesignResizeJobResponses,
      CreateDesignResizeJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/resizes",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * <Availability>
   *
   * To use this API, your integration must act on behalf of a user that's on a Canva plan with premium features (such as Canva Pro).
   *
   * Users on the Canva Free plan have access to a limited trial. For more information, see [Trial quotas](https://www.canva.dev/docs/connect/api-requests-responses/#trial-quotas).
   *
   * </Availability>
   *
   * Gets the result of a design resize job that was created using the [Create design resize
   * job API](https://www.canva.dev/docs/connect/api-reference/resizes/create-design-resize-job/).
   *
   * If the job is successful, the response includes a summary of the new resized design, including its metadata.
   *
   * You might need to make multiple requests to this endpoint until you get a `success` or `failed` status.
   * For more information on the workflow for using asynchronous jobs,
   * see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
   */
  public static getDesignResizeJob<ThrowOnError extends boolean = false>(
    options: Options<GetDesignResizeJobData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetDesignResizeJobResponses,
      GetDesignResizeJobErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/resizes/{jobId}",
      ...options,
    });
  }
}

export class UserService {
  /**
   * Returns the User ID and Team ID of the user
   * account associated with the provided access token.
   */
  public static usersMe<ThrowOnError extends boolean = false>(
    options?: Options<UsersMeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      UsersMeResponses,
      UsersMeErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/users/me",
      ...options,
    });
  }

  /**
   * Lists the API capabilities for the user account associated with the provided access token. For more information, see [Capabilities](https://www.canva.dev/docs/connect/capabilities/).
   */
  public static getUserCapabilities<ThrowOnError extends boolean = false>(
    options?: Options<GetUserCapabilitiesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetUserCapabilitiesResponses,
      GetUserCapabilitiesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/users/me/capabilities",
      ...options,
    });
  }

  /**
   * Currently, this returns the display name of the user account associated with the provided access token. More user information is expected to be included in the future.
   */
  public static getUserProfile<ThrowOnError extends boolean = false>(
    options?: Options<GetUserProfileData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetUserProfileResponses,
      GetUserProfileErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/v1/users/me/profile",
      ...options,
    });
  }
}
