import type { Broker } from "@realty-demo/shared-models";

const BACKEND_URL = process.env.BACKEND_URL;

export const brokers: Broker[] = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "s.johnson@fakemail.com",
    phone: "(000) 000-0001",
    licenseNumber: "FAKE-00000001",
    office: "Fake Office 1",
    salesVolume: 12500000,
    activeListings: 1,
    specialty: "High-End Specialist",
    imageUrl: `${BACKEND_URL}/public/images/broker-1.png`,
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "m.chen@fakemail.com",
    phone: "(000) 000-0002",
    licenseNumber: "FAKE-00000002",
    office: "Fake Office 2",
    salesVolume: 8750000,
    activeListings: 2,
    specialty: "High-End Specialist",
    imageUrl: `${BACKEND_URL}/public/images/broker-2.png`,
  },
  {
    id: 3,
    name: "Jessica Rodriguez",
    email: "j.rodriguez@fakemail.com",
    phone: "(000) 000-0003",
    licenseNumber: "FAKE-00000003",
    office: "Fake Office 3",
    salesVolume: 15200000,
    activeListings: 3,
    specialty: "Waterfront Specialist",
    imageUrl: `${BACKEND_URL}/public/images/broker-3.png`,
  },
  {
    id: 4,
    name: "David Wilson",
    email: "d.wilson@fakemail.com",
    phone: "(000) 000-0004",
    licenseNumber: "FAKE-00000004",
    office: "Fake Office 4",
    salesVolume: 9500000,
    activeListings: 4,
    specialty: "Waterfront Specialist",
    imageUrl: `${BACKEND_URL}/public/images/broker-4.png`,
  },
  {
    id: 5,
    name: "Olivia Kim",
    email: "o.kim@fakemail.com",
    phone: "(000) 000-0005",
    licenseNumber: "FAKE-00000005",
    office: "Fake Office 5",
    salesVolume: 11800000,
    activeListings: 5,
    specialty: "Appraisal Specialist",
    imageUrl: `${BACKEND_URL}/public/images/broker-5.png`,
  },
  {
    id: 6,
    name: "James Smith",
    email: "j.smith@fakemail.com",
    phone: "(000) 000-0006",
    licenseNumber: "FAKE-00000006",
    office: "Fake Office 6",
    salesVolume: 7500000,
    activeListings: 6,
    specialty: "Appraisal Specialist",
    imageUrl: `${BACKEND_URL}/public/images/broker-6.png`,
  },
];
