import type { Property } from "@realty-demo/shared-models";

// Use placeholder images from a reliable service
const getPropertyImages = (id: number) => {
  const BACKEND_URL = process.env.BACKEND_URL;
  return [
    `${BACKEND_URL}/public/images/property-${id}-exterior.jpg`,
    `${BACKEND_URL}/public/images/property-interior.jpg`,
    `${BACKEND_URL}/public/images/property-backyard.jpg`,
  ];
};

export const properties: Property[] = [
  {
    id: 1,
    title: "Elegant Victorian in Prime Location",
    address: "123 Main Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94105",
    price: 1250000,
    bedrooms: 3,
    bathrooms: 2,
    carSpots: 2,
    squareFeet: 1850,
    description:
      "Beautiful Victorian home with modern upgrades, hardwood floors, and a spacious backyard.",
    type: "single-family",
    status: "for-sale",
    imageUrls: getPropertyImages(1),
  },
  {
    id: 2,
    title: "Modern City View Condo",
    address: "456 Park Avenue",
    city: "San Francisco",
    state: "CA",
    zipCode: "94107",
    price: 895000,
    bedrooms: 2,
    bathrooms: 2,
    carSpots: 1,
    squareFeet: 1200,
    description:
      "Modern condo with floor-to-ceiling windows, luxury finishes, and amazing city views.",
    type: "condo",
    status: "for-sale",
    imageUrls: getPropertyImages(2),
  },
  {
    id: 3,
    title: "Luxurious Beachfront Estate",
    address: "789 Ocean Drive",
    city: "San Francisco",
    state: "CA",
    zipCode: "94121",
    price: 3500000,
    bedrooms: 5,
    bathrooms: 4,
    carSpots: 3,
    squareFeet: 3200,
    description:
      "Luxurious beachfront property with expansive ocean views, gourmet kitchen, and private pool.",
    type: "single-family",
    status: "for-sale",
    imageUrls: getPropertyImages(3),
  },
  {
    id: 4,
    title: "Contemporary Mountain View Home",
    address: "101 Mountain View",
    city: "Palo Alto",
    state: "CA",
    zipCode: "94301",
    price: 2200000,
    bedrooms: 4,
    bathrooms: 3,
    carSpots: 2,
    squareFeet: 2500,
    description:
      "Contemporary home with open floor plan, chef's kitchen, and backyard with mountain views.",
    type: "single-family",
    status: "for-sale",
    imageUrls: getPropertyImages(4),
  },
  {
    id: 5,
    title: "Modern Tech District Studio",
    address: "222 Tech Plaza",
    city: "Palo Alto",
    state: "CA",
    zipCode: "94304",
    price: 5000,
    bedrooms: 1,
    bathrooms: 1,
    carSpots: 1,
    squareFeet: 800,
    description:
      "Modern apartment in the heart of Silicon Valley, walk to shops and restaurants.",
    type: "condo",
    status: "for-rent",
    imageUrls: getPropertyImages(5),
  },
  {
    id: 6,
    title: "Panoramic Hillside Townhouse",
    address: "333 Hillside Terrace",
    city: "San Mateo",
    state: "CA",
    zipCode: "94403",
    price: 1750000,
    bedrooms: 3,
    bathrooms: 2.5,
    carSpots: 2,
    squareFeet: 2100,
    description:
      "Beautiful townhouse with panoramic hillside views, updated kitchen, and private patio.",
    type: "townhouse",
    status: "for-sale",
    imageUrls: getPropertyImages(6),
  },
  {
    id: 7,
    title: "Bay View Family Haven",
    address: "444 Bayview Lane",
    city: "San Rafael",
    state: "CA",
    zipCode: "94901",
    price: 1950000,
    bedrooms: 4,
    bathrooms: 3,
    carSpots: 2,
    squareFeet: 2800,
    description:
      "Spacious family home with bay views, updated throughout, large backyard with deck.",
    type: "single-family",
    status: "for-sale",
    imageUrls: getPropertyImages(7),
  },
  {
    id: 8,
    title: "Industrial Chic Downtown Loft",
    address: "555 Downtown Lofts",
    city: "San Francisco",
    state: "CA",
    zipCode: "94103",
    price: 3500,
    bedrooms: 2,
    bathrooms: 2,
    carSpots: 1,
    squareFeet: 1100,
    description:
      "Industrial-chic loft with high ceilings, exposed brick, and modern amenities.",
    type: "condo",
    status: "for-rent",
    imageUrls: getPropertyImages(8),
  },
  {
    id: 9,
    title: "Traditional Suburban Retreat",
    address: "666 Suburban Circle",
    city: "Walnut Creek",
    state: "CA",
    zipCode: "94596",
    price: 1325000,
    bedrooms: 4,
    bathrooms: 2.5,
    carSpots: 2,
    squareFeet: 2200,
    description:
      "Traditional family home in excellent school district, updated kitchen, large yard.",
    type: "single-family",
    status: "for-sale",
    imageUrls: getPropertyImages(9),
  },
];
